// QueueWebApplication/src/QueueWebApplication.SPA/src/components/ServerCard.tsx
import { type ReactNode, useEffect, useState } from 'react';
import { Button, Divider, Section, Stack } from 'tgui-core/components';
import { classes } from 'tgui-core/react';
import { QueueResponse, QueueState } from '../common/enums';
import type { PlayerData, Server } from '../common/interfaces';

interface ServerCardProps {
  server: Server;
  playerData: PlayerData;
}

export function ServerCard({ server, playerData }: ServerCardProps) {
  const [queueState, setQueueState] = useState(QueueState.NotInQueue);
  const queuePosition = server.queuePosition;

  const banned = playerData.banned;
  const notWhitelisted = server.whitelisted && !playerData.whitelistPasses?.includes(server.port);
  const disabled = banned || notWhitelisted;

  useEffect(() => {
    if (server.maximumPlayers === -1) {
      setQueueState(QueueState.AllowedToConnect);
    }

    if (queuePosition === 0) {
      setQueueState(QueueState.AllowedToConnect);
    }
  }, [queuePosition, server.maximumPlayers]);

  const serverUrl = `byond://${server.ipAddress}:${server.port}`;
  async function connectToQueue() {
    const response = await fetch(`/queue/add-client?serverName=${server.name}`, {
      method: 'POST',
    }).then((r) => r.json());

    switch (response) {
      case QueueResponse.AddedToQueue:
        setQueueState(QueueState.InQueue);
        break;
      case QueueResponse.BypassedQueue:
        setQueueState(QueueState.AllowedToConnect);
        playHornSound();
        break;
      case QueueResponse.Rejected:
        throw new Error("You shouldn't be able to press connect button");
    }
  }

  function playHornSound() {
    const sound = new Audio('/sounds/adminhelp.ogg');
    sound.load();
    sound.volume = 0.15;
    sound.play().catch(() => {});
  }

  function getTooltipText() {
    if (banned) {
      return 'Вы не можете играть, так как у вас бан!';
    } else if (notWhitelisted) {
      return 'У вас отсутствует вайтлист на этот сервер!';
    }
  }

  function getColor() {
    if (disabled) {
      return 'bad';
    }

    switch (queueState) {
      case QueueState.AllowedToConnect:
        return 'good';
      case QueueState.Banned:
        return 'bad';
      case QueueState.InQueue:
        return 'warning';
    }
  }

  return (
    <Section
      fill
      title={server.name}
      className={classes(['ServerCard', server.whitelisted && 'ServerCard--whitelisted'])}
    >
      <Stack.Item className="ServerCard__Content">
        <ServerInfo title="Онлайн">
          {server.currentPlayers}/{server.maximumPlayers}
        </ServerInfo>
        <Divider />
        <ServerInfo title="Очередь">{server.queuePosition === 0 ? 'Отсутствует' : server.queuePosition}</ServerInfo>
      </Stack.Item>
      <Stack.Item className="ServerCard__Join">
        <Button
          fluid
          tooltip={getTooltipText()}
          color={getColor()}
          disabled={disabled}
          onClick={queueState === QueueState.AllowedToConnect ? () => window.open(serverUrl) : connectToQueue}
        >
          {queueState === QueueState.InQueue ? `В очереди (${queuePosition}й)` : 'Присоединиться'}
        </Button>
      </Stack.Item>
    </Section>
  );
}

type ServerInfoProps = {
  title: string;
  children: ReactNode;
};

function ServerInfo(props: ServerInfoProps) {
  const { title, children } = props;
  return (
    <div className="ServerCard__Info">
      <div className="ServerCard__Info--name">{title}</div>
      <div className="ServerCard__Info--content">{children}</div>
    </div>
  );
}

// QueueWebApplication/src/QueueWebApplication.SPA/src/app/server-card/server-card.component.ts
import { Component, computed, input, OnInit } from '@angular/core';
import { takeUntilDestroyed, toObservable } from '@angular/core/rxjs-interop';
import { AsyncPipe, NgClass, NgIf } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { Server } from '../interfaces/server';
import { PlayerData } from '../interfaces/player-data';
import { QueueState } from '../enums/queue-state';
import { QueueResponse } from '../enums/queue-response';
import { firstValueFrom } from 'rxjs';
import { ButtonComponent } from '../components/button/button.component';

@Component({
  selector: 'app-server-card',
  standalone: true,
  imports: [AsyncPipe, NgClass, NgIf, ButtonComponent],
  templateUrl: './server-card.component.html',
  styleUrl: './server-card.component.scss',
})
export class ServerCardComponent implements OnInit {
  server = input.required<Server>();
  playerData = input.required<PlayerData>();
  queueState = QueueState.NotInQueue;
  queuePosition$ = toObservable(computed(() => this.server().queuePosition + 1));
  disabled$ = toObservable(
    computed(() => {
      const playerData = this.playerData();
      const server = this.server();
      const notWhitelisted = server.whitelisted && !playerData.whitelistPasses.includes(server.port);
      return playerData.banned || notWhitelisted;
    }),
  );
  serverUrl: string = 'Error';
  protected readonly QueueState = QueueState;
  constructor(private http: HttpClient) {
    this.queuePosition$.pipe(takeUntilDestroyed()).subscribe((position) => {
      if (position == 0) {
        this.queueState = QueueState.AllowedToConnect;
        this.playHornSound();
      }
    });
  }

  ngOnInit() {
    this.serverUrl = `byond://${this.server().ipAddress}:${this.server().port}`;
    if (this.server().maximumPlayers == -1) {
      this.queueState = QueueState.AllowedToConnect;
    }
  }

  async connectToQueue() {
    const response = await firstValueFrom(
      this.http.post<QueueResponse>('/queue/add-client?serverName=' + this.server().name, {}),
    );
    switch (response) {
      case QueueResponse.AddedToQueue:
        this.queueState = QueueState.InQueue;
        break;
      case QueueResponse.BypassedQueue:
        this.queueState = QueueState.AllowedToConnect;
        this.playHornSound();
        break;
      case QueueResponse.Rejected:
        throw new Error("You shouldn't be able to press connect button");
    }
  }

  private playHornSound() {
    const sound = new Audio('../assets/sounds/adminhelp.ogg');
    sound.load();
    sound.play().then();
  }
}

<div class="server-card" [ngClass]="{ 'whitelist-server': server().whitelisted }">
  <div class="server-card__name">{{ server().name }}</div>
  <div class="server-card__content">
    <div class="server-card__content-info">
      <div class="server-card__info-online">
        Онлайн: {{ server().currentPlayers }} /
        <i *ngIf="server().maximumPlayers === -1; else maxPlayers" class="fas fa-infinity"></i>
        <ng-template #maxPlayers>{{ server().maximumPlayers }}</ng-template>
      </div>
    </div>
    <div class="server-card__content-buttons">
      @switch (queueState) {
        @case (QueueState.NotInQueue) {
          <app-button [fluid]="true" [disabled]="disabled$ | async" (onClick)="connectToQueue()">
            {{ server().currentPlayers < server().maximumPlayers ? "Играть" : "В очередь" }}
          </app-button>
        }
        @case (QueueState.InQueue) {
          <app-button [fluid]="true" color="'purple'" [disabled]="disabled$ | async">
            Вы {{ queuePosition$ | async }}й в очереди
          </app-button>
        }
        @case (QueueState.AllowedToConnect) {
          <app-button
            [fluid]="true"
            [color]="server().whitelisted ? 'orange' : 'green'"
            [disabled]="disabled$ | async"
            link="{{ serverUrl }}">
            Играть
          </app-button>
        }
      }
    </div>
  </div>
</div>
